//! The app's identity to the OS: its icon and, on Linux, the id that ties its
//! windows to `tod.desktop`.
//!
//! Each platform takes the icon from a different place:
//! - Windows reads it from the exe's resources (`crates/tod/build.rs`).
//! - macOS: a bare binary has no bundle icon, so [`set_dock_icon`] sets it at
//!   startup for the Dock and the app switcher.
//! - Linux: Wayland shells find the icon through the `.desktop` file whose name
//!   matches the window's app id (installed by `scripts/install.sh`); X11
//!   also takes a per-window icon, set by [`window_options`].
//!
//! The artwork is generated by `assets/icon/make_icon.py`.

use gpui::WindowOptions;

/// The Wayland app id and X11 `WM_CLASS`; must match `tod.desktop`'s name.
pub const APP_ID: &str = "tod";

#[cfg_attr(target_os = "windows", allow(dead_code))]
const ICON_PNG: &[u8] = include_bytes!("../../../../assets/icon/png/tod-512.png");

/// Defaults for every window the app opens: use as the base of a
/// `WindowOptions { .., ..app_icon::window_options() }` literal.
pub fn window_options() -> WindowOptions {
    WindowOptions {
        app_id: Some(APP_ID.to_string()),
        icon: x11_icon(),
        ..Default::default()
    }
}

#[cfg(any(target_os = "linux", target_os = "freebsd"))]
fn x11_icon() -> Option<std::sync::Arc<image::RgbaImage>> {
    use std::sync::{Arc, OnceLock};
    static ICON: OnceLock<Option<Arc<image::RgbaImage>>> = OnceLock::new();
    ICON.get_or_init(|| {
        image::load_from_memory_with_format(ICON_PNG, image::ImageFormat::Png)
            .map(|img| Arc::new(img.into_rgba8()))
            .inspect_err(|err| tracing::warn!(%err, "failed to decode the app icon"))
            .ok()
    })
    .clone()
}

#[cfg(not(any(target_os = "linux", target_os = "freebsd")))]
fn x11_icon() -> Option<std::sync::Arc<image::RgbaImage>> {
    None
}

/// Sets the Dock and app-switcher icon. Call once on the main thread, after
/// the app has started.
#[cfg(target_os = "macos")]
pub fn set_dock_icon() {
    use objc2::AllocAnyThread;
    use objc2::MainThreadMarker;
    use objc2_app_kit::{NSApplication, NSImage};
    use objc2_foundation::NSData;

    let Some(mtm) = MainThreadMarker::new() else {
        tracing::warn!("set_dock_icon called off the main thread");
        return;
    };
    let data = NSData::with_bytes(ICON_PNG);
    let Some(image) = NSImage::initWithData(NSImage::alloc(), &data) else {
        tracing::warn!("failed to decode the app icon");
        return;
    };
    // SAFETY: on the main thread, with an image that stays alive for the call.
    unsafe { NSApplication::sharedApplication(mtm).setApplicationIconImage(Some(&image)) };
}

#[cfg(not(target_os = "macos"))]
pub fn set_dock_icon() {}
